

-- -----------------------------------------------------
-- Table mydb.FACTURAS
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS mydb.FACTURAS (
  id INT NULL,
  subtotal DECIMAL NOT NULL,
  descuento_aplicado DECIMAL NULL,
  total DECIMAL NOT NULL,
  metodo_pago VARCHAR(150) NOT NULL,
  estado VARCHAR(55) NULL,
  fecha_pago DATETIME GENERATED ALWAYS AS () VIRTUAL,
  TARIFAS_id INT NOT NULL,
  INGRESO_SALIDA_id INT NOT NULL,
  RESERVA_USUARIO_id INT NOT NULL,
  PRIMARY KEY (id, TARIFAS_id),
  CONSTRAINT fk_FACTURAS_TARIFAS1
    FOREIGN KEY (TARIFAS_id)
    REFERENCES mydb.TARIFAS (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_FACTURAS_INGRESO_SALIDA1
    FOREIGN KEY (INGRESO_SALIDA_id)
    REFERENCES mydb.INGRESO_SALIDA (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_FACTURAS_RESERVA1
    FOREIGN KEY (RESERVA_USUARIO_id)
    REFERENCES mydb.RESERVA (USUARIO_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


CREATE UNIQUE INDEX idFacturas_UNIQUE ON mydb.FACTURAS (id ASC) VISIBLE;

CREATE UNIQUE INDEX estado_UNIQUE ON mydb.FACTURAS (estado ASC) VISIBLE;

CREATE INDEX fk_FACTURAS_TARIFAS1_idx ON mydb.FACTURAS (TARIFAS_id ASC) VISIBLE;

CREATE INDEX fk_FACTURAS_INGRESO_SALIDA1_idx ON mydb.FACTURAS (INGRESO_SALIDA_id ASC) VISIBLE;

CREATE INDEX fk_FACTURAS_RESERVA1_idx ON mydb.FACTURAS (RESERVA_USUARIO_id ASC) VISIBLE;