

-- -----------------------------------------------------
-- Table mydb.RECONOCIMIENTO_PLACA
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS mydb.RECONOCIMIENTO_PLACA (
  idREconocimientoPlaca INT NOT NULL,
  id_vehiculo INT NOT NULL,
  placa VARCHAR(45) NOT NULL,
  fecha_hora DATETIME GENERATED ALWAYS AS (),
  imagen VARCHAR(250) NOT NULL,
  confianza DECIMAL NULL,
  VEHICULO_id INT NOT NULL,
  VEHICULO_ADMINISTRADOR_id INT NOT NULL,
  VEHICULO_USUARIO_id INT NOT NULL,
  PRIMARY KEY (idREconocimientoPlaca),
  CONSTRAINT fk_RECONOCIMIENTO_PLACA_VEHICULO1
    FOREIGN KEY (VEHICULO_id , VEHICULO_ADMINISTRADOR_id , VEHICULO_USUARIO_id)
    REFERENCES mydb.VEHICULO (id , ADMINISTRADOR_id , USUARIO_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


CREATE UNIQUE INDEX confianza_UNIQUE ON mydb.RECONOCIMIENTO_PLACA (confianza ASC) VISIBLE;

CREATE INDEX fk_RECONOCIMIENTO_PLACA_VEHICULO1_idx ON mydb.RECONOCIMIENTO_PLACA (VEHICULO_id ASC, VEHICULO_ADMINISTRADOR_id ASC, VEHICULO_USUARIO_id ASC) VISIBLE;
