

-- -----------------------------------------------------
-- Table mydb.RESERVA
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS mydb.RESERVA (
  ESPACIOS_id INT NOT NULL,
  USUARIO_id INT NOT NULL,
  PRIMARY KEY (ESPACIOS_id, USUARIO_id),
  CONSTRAINT fk_ESPACIOS_has_USUARIO_ESPACIOS1
    FOREIGN KEY (ESPACIOS_id)
    REFERENCES mydb.ESPACIOS (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ESPACIOS_has_USUARIO_USUARIO1
    FOREIGN KEY (USUARIO_id)
    REFERENCES mydb.USUARIO (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;

CREATE INDEX fk_ESPACIOS_has_USUARIO_USUARIO1_idx ON mydb.RESERVA (USUARIO_id ASC) VISIBLE;

CREATE INDEX fk_ESPACIOS_has_USUARIO_ESPACIOS1_idx ON mydb.RESERVA (ESPACIOS_id ASC) VISIBLE;
