

-- -----------------------------------------------------
-- Table mydb.ROLE_PERMISOS
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS mydb.ROLE_PERMISOS (
  USUARIO_id INT NOT NULL,
  PERMISOS_id INT NOT NULL,
  PRIMARY KEY (USUARIO_id, PERMISOS_id),
  CONSTRAINT fk_USUARIO_has_PERMISOS_USUARIO1
    FOREIGN KEY (USUARIO_id)
    REFERENCES mydb.USUARIO (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_USUARIO_has_PERMISOS_PERMISOS1
    FOREIGN KEY (PERMISOS_id)
    REFERENCES mydb.PERMISOS (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


CREATE INDEX fk_USUARIO_has_PERMISOS_PERMISOS1_idx ON mydb.ROLE_PERMISOS (PERMISOS_id ASC) VISIBLE;

CREATE INDEX fk_USUARIO_has_PERMISOS_USUARIO1_idx ON mydb.ROLE_PERMISOS (USUARIO_id ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;