

-- -----------------------------------------------------
-- Table mydb.USUARIO
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS mydb.USUARIO (
  id INT NOT NULL AUTO_INCREMENT,
  tipo_documento VARCHAR(55) NOT NULL,
  documento VARCHAR(45) NOT NULL,
  primer_nombre VARCHAR(45) NOT NULL,
  segundo_nombre VARCHAR(45) NULL,
  primer_apellido VARCHAR(45) NOT NULL,
  segundo_apellido VARCHAR(45) NULL,
  correo_electronico VARCHAR(45) NOT NULL,
  celular VARCHAR(45) NOT NULL,
  foto VARCHAR(255) NULL,
  contrasena VARCHAR(255) NOT NULL,
  PERFIL_USUARIO_id INT NOT NULL,
  MEMBRESIAS_id INT NOT NULL,
  PRIMARY KEY (id, PERFIL_USUARIO_id, MEMBRESIAS_id),
  CONSTRAINT fk_USUARIO_PERFIL_USUARIO1
    FOREIGN KEY (PERFIL_USUARIO_id)
    REFERENCES mydb.PERFIL_USUARIO (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_USUARIO_MEMBRESIAS1
    FOREIGN KEY (MEMBRESIAS_id)
    REFERENCES mydb.MEMBRESIAS (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;



CREATE UNIQUE INDEX documento_UNIQUE ON mydb.USUARIO (documento ASC) VISIBLE;

CREATE INDEX fk_USUARIO_PERFIL_USUARIO1_idx ON mydb.USUARIO (PERFIL_USUARIO_id ASC) VISIBLE;

CREATE INDEX fk_USUARIO_MEMBRESIAS1_idx ON mydb.USUARIO (MEMBRESIAS_id ASC) VISIBLE;
