

-- -----------------------------------------------------
-- Table mydb.VEHICULO
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS mydb.VEHICULO (
  id INT NOT NULL AUTO_INCREMENT,
  placa VARCHAR(45) NOT NULL,
  tipo ENUM('carro', 'moto') NOT NULL,
  color VARCHAR(45) NOT NULL,
  marca VARCHAR(45) NOT NULL,
  modelo VARCHAR(50) NOT NULL,
  ADMINISTRADOR_id INT NOT NULL,
  USUARIO_id INT NOT NULL,
  USUARIO_ROLES_PERMISOS_id INT NOT NULL,
  PRIMARY KEY (id, ADMINISTRADOR_id, USUARIO_id, USUARIO_ROLES_PERMISOS_id),
  CONSTRAINT fk_VEHICULO_USUARIO1
    FOREIGN KEY (USUARIO_id)
    REFERENCES mydb.USUARIO (id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;


CREATE UNIQUE INDEX placa_UNIQUE ON mydb.VEHICULO (placa ASC) VISIBLE;

CREATE INDEX fk_VEHICULO_USUARIO1_idx ON mydb.VEHICULO (USUARIO_id ASC, USUARIO_ROLES_PERMISOS_id ASC) VISIBLE;
